### ISSUE TITLE
Anmeldung für registrierte Nutzer

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#10]
### User-Story:

Als Nutzer (unabhängig der Rolle) möchte ich die Möglichkeit haben, mich über ein Login-System mit meinem Benutzerprofil anzumelden.

**ToDo**
- [x] Design-Dokumente erstellen
- [x] Backend Implementierung
- [x] Frontend Implementierung
- [x] Test
    - [x] Fehlt: Fehlermeldung bei falschen/fehlenden Eingaben (siehe UF1)
    - [x] Bug: Message für Erfolgreiche Anmeldung wird in JSON-Format angezeigt.
    - [x] Fehlt: Redirect auf Bibliothek nach erfolgreicher Anmeldung (siehe UF1)
- [x] Dokumentation
    - [x] Wireframes Updaten (View: Login, View: Registrieren)

### Acceptance Criteria:
**1. Login**
- [x] Die Quiz-Anwendung verfügt über eine Login-Seite.
- [x] Auf der Login-Seite sind Eingabefelder für Benutzername, Passwort sowie einen Button vorhanden, um sich anzumelden.

**2. Benutzerauthentifizierung:**

- [x] Die Pflichtfelder für Benutzername und Passwort müssen ausgefüllt sein.
- [x] Sind die Benutzerdaten korrekt eingegeben, wird der Benutzer zur Startseite weitergeleitet.
- [x] Sind die Benutzerdaten nicht korrekt eingegeben, erhält der Benutzer eine Fehlermeldung.

**3. Layout & Bedienung**
- [x] Layout entspricht den definierten Wireframes (Usermanagement).
- [ ] Layout im Detail entspricht dem definierten Mockup.
- [x] Bedienung der Pages entspricht den definierten Userflow-Charts (Usermanagement).

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [x] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
