### ISSUE TITLE
Datenbank für persistente Datenhaltung definieren und bereitstellen

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#11]
Implementierung einer Datenbank und herstellen der Datenbankverbindung, um Daten persistent speichern zu können.

**ToDo**
- [x] Auswahl des DBMS
- [x] Dokumente zur Datenbankmodellierung erstellen
- [x] Installation und Verbindung
- [x] Dokumentation

**Notizen**
- Auswahl: SQLite
