### ISSUE TITLE
Basis UX definieren

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#12]
**ToDo**
- [x] Definition der mindestens benötigten Views
- [x] Wireframes zur Basisarchitektur
- [x] Flowcharts für das Login und die Bibliothek
- [x] Mockup der Basisarchitektur/Bibliothek
