### ISSUE TITLE
Quizaufgaben werden persistent gespeichert

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#14]
### User-Story:

Als Benutzer und Dozent möchte ich, dass hinterlegte Quizaufgaben dauerhaft gespeichert werden, um permanent in Fragenpools hinterlegt zu sein.

**ToDo**
- [x] Datenmodell erstellen
- [x] Datenmodell implementieren
- [x] Dokumentation

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [x] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_ Mario
_Datum:_ 13.09.2024
