### ISSUE TITLE
Fragenpool anlegen / bearbeiten / löschen

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#15]
### User-Story:

Als Spieler und Dozent möchte ich Fragenpools zu bestimmten Themen anlegen, bearbeiten und löschen können, um Quizfragen darin thematisch zu sammeln.

Wcihtig: Implementierung erfolgt ivm. US2

**ToDo**
- [x] Design-Dokumente erstellen ivm. US2
- [x] Backend Implementierung
    - [x] #31
    - [x] Bug: Bei Namensänderung eines Quiztask wird auf Quizpool 1 Quiztask 1 gesprungen.
    - [x] Fehlt: Begrenzung auf 4 Antwortoptionen (UF6)
- [x] Frontend Implementierung
    - [x] Bootstrap implementieren 
- [x] Tests
- [x] Dokumentation

### Akzeptanzkriterien
- [x] Layout entspricht den definierten Wireframes (Library).
- [x] Layout im Detail entspricht dem definierten Mockup.
- [x] Bedienung der Pages entspricht den definierten Userflow-Charts (Library).

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [x] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
