### ISSUE TITLE
Persistente Speicherung der Benutzerprofile

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#18]
### User-Story:

Als Benutzer möchte ich, dass mein Benutzerprofil dauerhaft gespeichert wird, um eine wiederholte Nutzung der Anwendung zu ermöglichen.

**ToDo**
- [x] Design-Dokumente erstellen
- [x] Implementierung der Models und Forms
- [x] Implementierung der DB-Anbindung
- [x] Dokumentation

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [x] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_

### Acceptance Criteria:

**1. Persistente Speicherung**

- [x] Das Benutzerprofil wird nach klicken des Aktivierungslinks persistent in der Datenbank gespeichert.

**2. Benutzerprofil-Aktualisierung**

- [x] Änderungen von Benutzernamen, E-Mail Adresse, Passwort werden sofort persistent in der Datenbank gespeichert.

_Prüfung erfolgte durch:_ Mario
_Datum:_ 13.08.2024
