### ISSUE TITLE
Anpassen des Benutzerprofils

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#19]
### User-Story:

Als Benutzer möchte ich auch nach der Registrierung jederzeit meine Profildaten ändern können, um bei Bedarf bspw. mein Profilbild, Passwort oder Kontaktdaten ändern zu können.

**ToDo**
- [x] Design-Dokumente erstellen
- [x] Backend Implementierung
- [x] Frontend Implementierung
- [x] Tests:
    - [x] Fehlt: Feld zum Passwort ändern.
    - [x] Fehlt: Anzeige der Rolle.
    - [x] #35
    - [x] Optisch: Falsche Abstände bei den Buttons.
- [ ] Dokumentation

### Acceptance Criteria:

**1. Profilverwaltung**
- [x] Benutzer können auf ihrer Profilseite ihre Benutzerdaten (Benutzername, Mail, Passwort) ändern.

**2. Layout & Bedienung**
- [x] Layout entspricht den definierten Wireframes (Usermanagement).
- [x] Layout im Detail entspricht dem definierten Mockup.
- [x] Bedienung der Pages entspricht den definierten Userflow-Charts (Usermanagement).

### Definition of Done:

**1. Anforderungen erfüllt**

- [ ] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [ ] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [ ] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [ ] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [ ] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [ ] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
