### ISSUE TITLE
Löschen des Benutzerprofils

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#20]
### User-Story:

Als Benutzer möchte ich mein Benutzerprofil vollständig löschen können, damit keine Daten über mich gespeichert bleiben, falls ich die Anwendung nicht mehr nutzen möchte.

### Todo:

- [x] Tests
    - [x] Fehler: Profil wird nach Klick auf 'Löschen' nicht aus der DB gelöscht.
    - [x] Fehlt: Redirect auf Bibliothek nach löschen

### Akzeptanz
- [x] Löschfunktion wird auf der Profilseite bereitgestellt.
- [x] Die Löschfunktion löscht das Benutzerprofil sofort und dauerhaft.

**Layout & Bedienung**
- [x] Layout entspricht den definierten Wireframes (Usermanagement).
- [x] Layout im Detail entspricht dem definierten Mockup.
- [x] Bedienung der Pages entspricht den definierten Userflow-Charts (Usermanagement).

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [ ] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [ ] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [ ] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [ ] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
