### ISSUE TITLE
Spielerergebnisse werden persistent gespeichert

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#21]
### User-Story:

Als Spieler und Dozent möchte ich, dass die Quizergebnisse dauerhaft gespeichert werden, um Lernfortschritte auch über Zeit analysieren zu können.

**ToDo**
- [x] Testprotokoll
- [x] ORM implementieren (entsprechend ERM)
- [x] Testen

### Akzeptanzkriterien
- [x] ORM gemäß ERM implementiert
- [x] Reead/Write am DB Backend getestet

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [x] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
