### ISSUE TITLE
Student kann nur eigene Fragenpools löschen

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#33]
### User-Story:

Als Dozent und Betreiber möchte ich, dass Spieler nur ihre eigenen Quizaufgaben und Fragenpools löschen können, damit ein Spieler durch das löschen fremder Quizfragen und Fragenpools nicht die Nutzung der Anwendung stören kann.

**Todo**
- [x] Zusammenführen mit RR-Konzept

### Definition of Done:

**1. Anforderungen erfüllt**

- [ ] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [ ] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
