### ISSUE TITLE
Dozent kann jeden Fragenpool löschen

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#34]
### User-Story:

Als Dozent möchte ich jeden Fragenpool löschen können, um veraltete oder falsche Quizfragen oder Fragenpools aus der Anwendung entfernen zu können.

**Todo**
- [ ] Zusammenführen mit RR-Konzept

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [x] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [ ] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [ ] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [x] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
