### ISSUE TITLE
Registrierung als Benutzer

### ISSUE THREAD

**Issue by fulcrum1991** [fulcrum1991/Quiz-App#7]
### User-Story:

Neue Benutzer müssen sich für die Nutzung der Anwendung registrieren und erhalten ein Benutzerprofil, um Aktionen in der Anwendung eindeutig zuordnen zu können und damit der Betreiber die Kontrolle über die Nutzung der Anwendung behält.

**ToDo**
- [x] Design-Dokumente erstellen
- [x] Backend Implementierung
- [x] Frontend Implementierung
- [x] Tests
    - [x] Fehlt: Fehlermeldung bei falschen/fehlenden Eingaben (siehe UF1)
    - [x] Bug: Message für Erfolgreiche Anmeldung wird in JSON-Format angezeigt.
    - [x] Fehlt: Erfolgsmeldung und Redirect auf Bibliothek nach erfolgreicher Registrierung (siehe UF1)
    - [x] Fehlt: Zuordnung von User zu Gruppe im ORM. Bzw Abspeichern der Gruppenzugehörigkeit.
- [x] Dokumentation
    - [x] Wireframes Updaten (View: Login, View: Registrieren)

### Acceptance Criteria

**1. Registrierung**

- [x] Für neue Benutzer stellt die Quiz-Anwendung eine Seite zum registrieren zur Verfügung.
- [x] Die Seite zum registrieren verfügt über Eingabefelder für Benutzername, E-Mail Adresse und Passwort sowie über einen Button, um die Registrierung in Gang zu setzen.

**2. Validierung**

- [x] Die Pflichtfelder für Benutzername, E-Mail Adresse und Passwort müssen ausgefüllt sein.
- [x] Das Passwort muss mindestens 10 Zeichen lang sein und aus Buchstaben und Zahlen bestehen.
- [x] Bei E-Mail Adressen mit falschen Format und Passwörtern mit weniger als 10 Zeichen sowie Kombination aus Buchstaben und Zahlen wird eine Fehlermeldung angezeigt.

**3. Benutzerprofil**

- [x] Nach dem Bestätigen der Registrierung kann der Benutzer sich mit seinen Benutzerdaten auf der Website anmelden und hat Zugriff auf sein Benutzerkonto.

**4. Layout & Bedienung**
- [x] Layout entspricht den definierten Wireframes (Usermanagement).
- [x] Layout im Detail entspricht dem definierten Mockup.
- [x] Bedienung der Pages entspricht den definierten Userflow-Charts (Usermanagement).

### Definition of Done:

**1. Anforderungen erfüllt**

- [x] Alle vom Product Owner festgelegten Akzeptanzkriterien sind umgesetzt.

**2. Code-Review durchgeführt**

- [ ] Der Quellcode wurde von einem anderen Entwickler geprüft und als qualitativ hochwertig eingeschätzt.

**3. Unit-Tests erfolgreich**

- [x] Alle durchgeführten Unit-Tests waren fehlerfrei.

**4. Integrationstests erfolgreich**

- [x] Alle durchgeführten Integrationstests waren erfolgreich.

**5. Dokumentationsqualität**

- [x] Der Quellcode ist verständlich und ausreichend dokumentiert.

**6. Einhaltung Standards**

- [ ] Die Coding-Standards wurden eingehalten.

_Prüfung erfolgte durch:_
_Datum:_
